Repository Kernel360/Kernel360-KDEV4-ZIPLINE, pull requests merged in 2025-04, with the labels that each got.

#38 chore: 외부 api 호출을 위한 webClient 설정 추가
  build.gradle
  src/main/java/com/zipline/global/config/WebClientConfig.java
Labels: 🧹 Chore

#40 feat: 네이버 크롤러 구현
  src/main/java/com/zipline/controller/CrawlerController.java
  src/main/java/com/zipline/dto/RegionDto.java
  src/main/java/com/zipline/entity/PropertyArticle.java
  src/main/java/com/zipline/entity/Region.java
  src/main/java/com/zipline/global/exception/GlobalExceptionHandler.java
  src/main/java/com/zipline/global/exception/custom/CrawlingInProgressException.java
  src/main/java/com/zipline/repository/PropertyArticleRepository.java
  src/main/java/com/zipline/repository/RegionRepository.java
  src/main/java/com/zipline/service/NaverArticleService.java
  src/main/java/com/zipline/service/RegionCodeService.java
  src/main/java/com/zipline/service/UserService.java
  src/main/java/com/zipline/util/CoordinateUtil.java
  src/main/java/com/zipline/util/CrawlingStatusManager.java
  src/main/java/com/zipline/util/RandomSleepUtil.java
Labels: ✨ Feat

#41 feat: User 로그아웃
  src/main/java/com/zipline/controller/UserController.java
  src/main/java/com/zipline/entity/User.java
  src/main/java/com/zipline/global/config/SecurityConfig.java
  src/main/java/com/zipline/global/jwt/JwtFilter.java
  src/main/java/com/zipline/global/jwt/JwtSecurityConfig.java
  src/main/java/com/zipline/global/jwt/TokenProvider.java
  src/main/java/com/zipline/service/UserService.java
Labels: ✨ Feat

#51 fix: JWT 인증 예외 처리 위치 수정
  build.gradle
  src/main/java/com/zipline/global/common/response/ApiResponse.java
  src/main/java/com/zipline/global/config/SecurityConfig.java
  src/main/java/com/zipline/global/jwt/ErrorCode.java
  src/main/java/com/zipline/global/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/zipline/global/jwt/JwtFilter.java
  src/main/java/com/zipline/global/jwt/TokenProvider.java
Labels: 🛠️ Fix

#53 feat: 설문 생성
  src/main/java/com/zipline/entity/User.java
  src/main/java/com/zipline/global/exception/custom/ChoiceNotAllowedException.java
  src/main/java/com/zipline/survey/controller/SurveyController.java
  src/main/java/com/zipline/survey/dto/QuestionValidate.java
  src/main/java/com/zipline/survey/dto/QuestionValidator.java
  src/main/java/com/zipline/survey/dto/SurveyCreateRequestDTO.java
  src/main/java/com/zipline/survey/entity/Choice.java
  src/main/java/com/zipline/survey/entity/Question.java
  src/main/java/com/zipline/survey/entity/Survey.java
  src/main/java/com/zipline/survey/entity/enums/QuestionType.java
  src/main/java/com/zipline/survey/entity/enums/SurveyStatus.java
  src/main/java/com/zipline/survey/repository/ChoiceRepository.java
  src/main/java/com/zipline/survey/repository/QuestionRepository.java
  src/main/java/com/zipline/survey/repository/SurveyRepository.java
  src/main/java/com/zipline/survey/service/SurveyService.java
Labels: ✨ Feat

#56 feat: AccessToken 재발급
  src/main/java/com/zipline/controller/UserController.java
  src/main/java/com/zipline/dto/TokenRequestDTO.java
  src/main/java/com/zipline/dto/TokenResponseDTO.java
  src/main/java/com/zipline/dto/UserRequestDTO.java
  src/main/java/com/zipline/dto/UserResponseDTO.java
  src/main/java/com/zipline/entity/User.java
  src/main/java/com/zipline/global/config/SecurityConfig.java
  src/main/java/com/zipline/global/exception/GlobalExceptionHandler.java
  src/main/java/com/zipline/global/jwt/JwtFilter.java
  src/main/java/com/zipline/global/jwt/TokenProvider.java
  src/main/java/com/zipline/service/UserService.java
Labels: ✨ Feat

#57 feat: 고객 목록 조회
  src/main/java/com/zipline/controller/CustomerController.java
  src/main/java/com/zipline/dto/CustomerListResponseDTO.java
  src/main/java/com/zipline/dto/PageRequestDTO.java
  src/main/java/com/zipline/repository/CustomerRepository.java
  src/main/java/com/zipline/service/CustomerService.java
Labels: ✨ Feat

#59 feat: 생성한 설문 조회
  src/main/java/com/zipline/global/exception/custom/SurveyNotFoundException.java
  src/main/java/com/zipline/survey/controller/SurveyController.java
  src/main/java/com/zipline/survey/dto/ChoiceResponseDTO.java
  src/main/java/com/zipline/survey/dto/QuestionResponseDTO.java
  src/main/java/com/zipline/survey/dto/SurveyResponseDTO.java
  src/main/java/com/zipline/survey/repository/QuestionRepository.java
  src/main/java/com/zipline/survey/repository/SurveyRepository.java
  src/main/java/com/zipline/survey/service/SurveyService.java
Labels: ✨ Feat

#66 remove: RefreshToken 파일 삭제
  src/main/java/com/zipline/entity/RefreshToken.java
Labels: 🗑️ Remove

#64 feat: Survey, Question Field 추가
  src/main/java/com/zipline/survey/dto/QuestionResponseDTO.java
  src/main/java/com/zipline/survey/dto/SurveyCreateRequestDTO.java
  src/main/java/com/zipline/survey/dto/SurveyResponseDTO.java
  src/main/java/com/zipline/survey/entity/Question.java
  src/main/java/com/zipline/survey/entity/Survey.java
  src/main/java/com/zipline/survey/repository/QuestionRepository.java
  src/main/java/com/zipline/survey/service/SurveyService.java
Labels: ✨ Feat

#68 feat: 수동 매물 등록
  src/main/java/com/zipline/controller/PropertyController.java
  src/main/java/com/zipline/dto/AgentPropertyRequestDTO.java
  src/main/java/com/zipline/dto/AgentPropertyResponseDTO.java
  src/main/java/com/zipline/entity/AgentProperty.java
  src/main/java/com/zipline/entity/enums/PropertyCategory.java
  src/main/java/com/zipline/entity/enums/PropertyType.java
  src/main/java/com/zipline/global/exception/custom/PermissionDeniedException.java
  src/main/java/com/zipline/global/exception/custom/agentProperty/PropertyNotFoundException.java
  src/main/java/com/zipline/repository/AgentPropertyRepository.java
  src/main/java/com/zipline/service/AgentPropertyService.java
  src/main/java/com/zipline/service/CustomerService.java
Labels: ✨ Feat

#69 feat: 매물 상세 조회
  src/main/java/com/zipline/controller/agentProperty/AgentPropertyController.java
  src/main/java/com/zipline/dto/agentProperty/AgentPropertyRequestDTO.java
  src/main/java/com/zipline/dto/agentProperty/AgentPropertyResponseDTO.java
  src/main/java/com/zipline/entity/agentProperty/AgentProperty.java
  src/main/java/com/zipline/repository/agentProperty/AgentPropertyRepository.java
  src/main/java/com/zipline/service/agentProperty/AgentPropertyService.java
Labels: ✨ Feat

#80 feat: 상담 생성
  src/main/java/com/zipline/controller/counsel/CounselController.java
  src/main/java/com/zipline/dto/counsel/CounselCreateRequestDTO.java
  src/main/java/com/zipline/entity/counsel/Counsel.java
  src/main/java/com/zipline/entity/counsel/CounselDetail.java
  src/main/java/com/zipline/repository/counsel/CounselRepository.java
  src/main/java/com/zipline/service/counsel/CounselService.java
Labels: ✨ Feat, 🗑️ Remove

#79 feat: 매물 수정
  src/main/java/com/zipline/controller/agentProperty/AgentPropertyController.java
  src/main/java/com/zipline/dto/agentProperty/AgentPropertyRequestDTO.java
  src/main/java/com/zipline/dto/agentProperty/AgentPropertyResponseDTO.java
  src/main/java/com/zipline/entity/agentProperty/AgentProperty.java
  src/main/java/com/zipline/service/agentProperty/AgentPropertyService.java
Labels: ✨ Feat

#81 feat: 공개 매물 뷰
  src/main/java/com/zipline/controller/publicItem/PropertyArticleViewController.java
  src/main/java/com/zipline/dto/publicItem/PropertyArticlePageResponseDTO.java
  src/main/java/com/zipline/dto/publicItem/PropertyArticleSearchDTO.java
  src/main/java/com/zipline/dto/publicItem/PropertyArticleViewDTO.java
  src/main/java/com/zipline/global/exception/custom/publicItem/InvalidPropertySearchException.java
  src/main/java/com/zipline/global/exception/custom/publicItem/PropertyArticleNotFoundException.java
  src/main/java/com/zipline/repository/publicItem/PropertyArticleViewRepository.java
  src/main/java/com/zipline/repository/publicItem/PropertyArticleViewSpecification.java
  src/main/java/com/zipline/service/publicItem/PropertyArticleViewService.java
Labels: ✨ Feat

#89 feat: 계약 등록
  src/main/java/com/zipline/controller/agentProperty/AgentPropertyController.java
  src/main/java/com/zipline/controller/contract/ContractController.java
  src/main/java/com/zipline/dto/AgentPropertyListResponseDTO.java
  src/main/java/com/zipline/dto/agentProperty/AgentPropertyResponseDTO.java
  src/main/java/com/zipline/dto/contract/ContractRequestDTO.java
  src/main/java/com/zipline/dto/contract/ContractResponseDTO.java
  src/main/java/com/zipline/entity/agentProperty/AgentProperty.java
  src/main/java/com/zipline/entity/contract/Contract.java
  src/main/java/com/zipline/entity/contract/ContractDocument.java
  src/main/java/com/zipline/entity/contract/CustomerContract.java
  src/main/java/com/zipline/entity/enums/ContractStatus.java
  src/main/java/com/zipline/repository/agentProperty/AgentPropertyRepository.java
  src/main/java/com/zipline/repository/contract/ContractDocumentRepository.java
  src/main/java/com/zipline/repository/contract/ContractRepository.java
  src/main/java/com/zipline/repository/contract/CustomerContractRepository.java
  src/main/java/com/zipline/service/agentProperty/AgentPropertyService.java
  src/main/java/com/zipline/service/contract/ContractService.java
Labels: ✨ Feat

#90 feat: 상담 수정
  src/main/java/com/zipline/controller/counsel/CounselController.java
  src/main/java/com/zipline/dto/counsel/CounselModifyRequestDTO.java
  src/main/java/com/zipline/dto/counsel/CounselResponseDTO.java
  src/main/java/com/zipline/entity/counsel/Counsel.java
  src/main/java/com/zipline/entity/counsel/CounselDetail.java
  src/main/java/com/zipline/repository/counsel/CounselDetailRepository.java
  src/main/java/com/zipline/repository/counsel/CounselRepository.java
  src/main/java/com/zipline/service/counsel/CounselService.java
Labels: ✨ Feat

#87 feat: 매물 목록 조회
  src/main/java/com/zipline/controller/agentProperty/AgentPropertyController.java
  src/main/java/com/zipline/dto/agentProperty/AgentPropertyListResponseDTO.java
  src/main/java/com/zipline/entity/agentProperty/AgentProperty.java
  src/main/java/com/zipline/service/agentProperty/AgentPropertyService.java
Labels: ✨ Feat

#92 feat: 상담 삭제
  src/main/java/com/zipline/controller/counsel/CounselController.java
  src/main/java/com/zipline/entity/counsel/Counsel.java
  src/main/java/com/zipline/service/counsel/CounselService.java
Labels: ✨ Feat

#103 (chore)Redis_URL 등록
  src/main/resources/application-dev.yml
Labels: 🧹 Chore

#104 (chore)gitflow 업데이트
  .github/workflows/cicd.yml
Labels: 🧹 Chore

#99 feat: 제출된 설문 조회
  src/main/java/com/zipline/survey/controller/SurveyController.java
  src/main/java/com/zipline/survey/dto/SurveyResponseDetailDTO.java
  src/main/java/com/zipline/survey/entity/SurveyResponse.java
  src/main/java/com/zipline/survey/repository/SurveyAnswerRepository.java
  src/main/java/com/zipline/survey/repository/SurveyResponseRepository.java
  src/main/java/com/zipline/survey/service/SurveyAnswerFactory.java
  src/main/java/com/zipline/survey/service/SurveyService.java
Labels: ✨ Feat

#102 feat: 계약 등록 - 파일 업로드
  src/main/java/com/zipline/controller/contract/ContractController.java
  src/main/java/com/zipline/dto/contract/ContractRequestDTO.java
  src/main/java/com/zipline/entity/contract/Contract.java
  src/main/java/com/zipline/entity/contract/ContractDocument.java
  src/main/java/com/zipline/global/config/S3Folder.java
  src/main/java/com/zipline/global/util/FileValidator.java
  src/main/java/com/zipline/global/util/S3FileUploader.java
  src/main/java/com/zipline/service/contract/ContractService.java
Labels: ✨ Feat

#110 (fix)ci/cd
  .github/workflows/cicd.yml
Labels: 🔥 HotFix

#113 chore: cors 설정 추가
  src/main/java/com/zipline/global/config/CorsConfig.java
  src/main/java/com/zipline/global/config/SecurityConfig.java
Labels: 🧹 Chore

#111 (fix)cicd
  .github/workflows/cicd.yml
Labels: 🛠️ Fix

#116 feat: 제출된 설문 리스트 조회
  src/main/java/com/zipline/survey/controller/SurveyController.java
  src/main/java/com/zipline/survey/dto/SurveyResponseListDTO.java
  src/main/java/com/zipline/survey/repository/SurveyAnswerRepository.java
  src/main/java/com/zipline/survey/repository/SurveyResponseRepository.java
  src/main/java/com/zipline/survey/service/SurveyService.java
Labels: 🛠️ Fix, ✨ Feat

#124 fix: 고객 생성, 고객 수정 요청 시 주소 필수값 해제
  src/main/java/com/zipline/dto/CustomerModifyRequestDTO.java
  src/main/java/com/zipline/dto/CustomerRegisterRequestDTO.java
Labels: 🛠️ Fix

#122 feat: 설문 조회 및 설문 제출 접근 권한 수정
  src/main/java/com/zipline/global/config/SecurityConfig.java
Labels: ✨ Feat

#114 feat: User 회원가입 시 기본 설문 생성
  src/main/java/com/zipline/service/UserService.java
  src/main/java/com/zipline/survey/service/SurveyService.java
Labels: ✨ Feat

#128 feat: user 조회 시 응답 데이터 추가
  src/main/java/com/zipline/dto/UserResponseDTO.java
  src/main/java/com/zipline/service/UserService.java
  src/main/java/com/zipline/survey/repository/SurveyRepository.java
Labels: ✨ Feat

#126 feat: 계약 목록 조회
  src/main/java/com/zipline/controller/contract/ContractController.java
  src/main/java/com/zipline/dto/contract/ContractListResponseDTO.java
  src/main/java/com/zipline/dto/contract/ContractResponseDTO.java
  src/main/java/com/zipline/repository/contract/ContractRepository.java
  src/main/java/com/zipline/repository/contract/CustomerContractRepository.java
  src/main/java/com/zipline/service/contract/ContractService.java
Labels: ✨ Feat

#137 feat: 고객 정보 상세 조회 - 상담 내역 조회
  src/main/java/com/zipline/controller/CustomerController.java
  src/main/java/com/zipline/dto/counsel/CounselListResponseDTO.java
  src/main/java/com/zipline/repository/counsel/CounselRepository.java
  src/main/java/com/zipline/service/CustomerService.java
Labels: ✨ Feat

#141 fix: ContractListResponseDTO에 데이터 추가
  src/main/java/com/zipline/dto/contract/ContractListResponseDTO.java
Labels: 🛠️ Fix

#146 feat: 기능 별 목록 조회 시 내림차 순 조회
  src/main/java/com/zipline/repository/CustomerRepository.java
  src/main/java/com/zipline/repository/agentProperty/AgentPropertyRepository.java
  src/main/java/com/zipline/repository/contract/ContractDocumentRepository.java
  src/main/java/com/zipline/repository/contract/ContractRepository.java
  src/main/java/com/zipline/repository/contract/CustomerContractRepository.java
Labels: ✨ Feat

#148 feat: 고객 정보 상세 조회 - 계약 목록 조회
  src/main/java/com/zipline/controller/CustomerController.java
  src/main/java/com/zipline/repository/contract/CustomerContractRepository.java
  src/main/java/com/zipline/service/CustomerService.java
Labels: ✨ Feat

#154 Remove: 사용하지 않는 크롤링코드 제거
  src/main/java/com/zipline/controller/publicItem/NaverCrawlController.java
  src/main/java/com/zipline/controller/publicItem/NaverProxyCrawlController.java
  src/main/java/com/zipline/service/publicItem/NaverArticleService.java
  src/main/java/com/zipline/service/publicItem/ProxyNaverArticleService.java
Labels: 🗑️ Remove

#158 refactor: Service 레이어 인터페이스화
  apiserver/controller/src/main/java/com/zipline/controller/agentProperty/AgentPropertyController.java
  apiserver/controller/src/main/java/com/zipline/controller/counsel/CounselController.java
  apiserver/controller/src/main/java/com/zipline/controller/customer/CustomerController.java
  apiserver/controller/src/main/java/com/zipline/controller/survey/SurveyController.java
  apiserver/controller/src/main/java/com/zipline/controller/user/TokenResponseDTO.java
  apiserver/controller/src/main/java/com/zipline/controller/user/UserController.java
  apiserver/service/src/main/java/com/zipline/service/CustomUserDetailService.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/AgentPropertyService.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/AgentPropertyServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/contract/ContractService.java
  apiserver/service/src/main/java/com/zipline/service/contract/ContractServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/counsel/CounselService.java
  apiserver/service/src/main/java/com/zipline/service/counsel/CounselServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/customer/CustomerService.java
  apiserver/service/src/main/java/com/zipline/service/customer/CustomerServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/survey/SurveyService.java
  apiserver/service/src/main/java/com/zipline/service/survey/SurveyServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/user/UserService.java
  apiserver/service/src/main/java/com/zipline/service/user/UserServiceImpl.java
  crawlerserver/controller/src/main/java/com/zipline/controller/publicitem/NaverMigrationController.java
  crawlerserver/controller/src/main/java/com/zipline/controller/publicitem/NaverProxyRawArticleController.java
  crawlerserver/controller/src/main/java/com/zipline/controller/publicitem/NaverRawArticleController.java
  crawlerserver/controller/src/main/java/com/zipline/controller/publicitem/PropertyArticleViewController.java
  crawlerserver/controller/src/main/java/com/zipline/controller/publicitem/ProxyListUploadController.java
  crawlerserver/controller/src/main/java/com/zipline/controller/publicitem/RegionCrawlController.java
  crawlerserver/service/src/main/java/com/zipline/service/publicItem/NaverRawArticleMigrationService.java
  crawlerserver/service/src/main/java/com/zipline/service/publicItem/NaverRawArticleService.java
  crawlerserver/service/src/main/java/com/zipline/service/publicItem/PropertyArticleViewService.java
  crawlerserver/service/src/main/java/com/zipline/service/publicItem/ProxyListUploadService.java
  crawlerserver/service/src/main/java/com/zipline/service/publicItem/ProxyNaverRawArticleService.java
  crawlerserver/service/src/main/java/com/zipline/service/publicItem/RegionCodeService.java
Labels: ⚙️ Refactor

#168 fix: crawlerserver 누락된 serviceImpl 파일 추가
  crawlerserver/service/src/main/java/com/zipline/service/publicItem/NaverRawArticleMigrationServiceImpl.java
  crawlerserver/service/src/main/java/com/zipline/service/publicItem/NaverRawArticleServiceImpl.java
  crawlerserver/service/src/main/java/com/zipline/service/publicItem/PropertyArticleViewServiceimpl.java
  crawlerserver/service/src/main/java/com/zipline/service/publicItem/ProxyListUploadServiceImpl.java
  crawlerserver/service/src/main/java/com/zipline/service/publicItem/ProxyNaverRawArticleServiceImpl.java
  crawlerserver/service/src/main/java/com/zipline/service/publicItem/RegionCodeServiceImpl.java
Labels: 🛠️ Fix

#170 (Refactor) Entitiy 수정
  apiserver/domain/src/main/java/com/zipline/dto/CustomerDetailResponseDTO.java
  apiserver/domain/src/main/java/com/zipline/dto/CustomerModifyRequestDTO.java
  apiserver/domain/src/main/java/com/zipline/dto/CustomerRegisterRequestDTO.java
  apiserver/domain/src/main/java/com/zipline/dto/agentProperty/AgentPropertyRequestDTO.java
  apiserver/domain/src/main/java/com/zipline/dto/agentProperty/AgentPropertyResponseDTO.java
  apiserver/domain/src/main/java/com/zipline/dto/contract/ContractRequestDTO.java
  apiserver/domain/src/main/java/com/zipline/entity/BaseTimeEntity.java
  apiserver/domain/src/main/java/com/zipline/entity/agentProperty/AgentProperty.java
  apiserver/domain/src/main/java/com/zipline/entity/contract/Contract.java
  apiserver/domain/src/main/java/com/zipline/entity/contract/ContractDocument.java
  apiserver/domain/src/main/java/com/zipline/entity/contract/CustomerContract.java
  apiserver/domain/src/main/java/com/zipline/entity/counsel/Counsel.java
  apiserver/domain/src/main/java/com/zipline/entity/counsel/CounselDetail.java
  apiserver/domain/src/main/java/com/zipline/entity/customer/Customer.java
  apiserver/domain/src/main/java/com/zipline/entity/enums/ContractStatus.java
  apiserver/domain/src/main/java/com/zipline/entity/enums/CounselType.java
  apiserver/domain/src/main/java/com/zipline/entity/survey/Choice.java
  apiserver/domain/src/main/java/com/zipline/entity/survey/Question.java
  apiserver/domain/src/main/java/com/zipline/entity/survey/Survey.java
  apiserver/domain/src/main/java/com/zipline/entity/survey/SurveyAnswer.java
  apiserver/domain/src/main/java/com/zipline/entity/survey/SurveyResponse.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/CustomerRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/agentProperty/AgentPropertyRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/contract/ContractRepository.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/AgentPropertyServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/contract/ContractServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/counsel/CounselServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/customer/CustomerServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/survey/SurveyAnswerFactory.java
Labels: ⚙️ Refactor

#172 feat: 아이디 찾기 기능 구현
  apiserver/common/src/main/java/com/zipline/global/config/SecurityConfig.java
  apiserver/controller/src/main/java/com/zipline/controller/user/UserController.java
  apiserver/domain/src/main/java/com/zipline/dto/user/FindUserIdRequestDTO.java
  apiserver/domain/src/main/java/com/zipline/dto/user/FindUserIdResponseDTO.java
  apiserver/domain/src/main/java/com/zipline/dto/user/TokenRequestDTO.java
  apiserver/domain/src/main/java/com/zipline/dto/user/TokenResponseDTO.java
  apiserver/domain/src/main/java/com/zipline/dto/user/UserRequestDTO.java
  apiserver/domain/src/main/java/com/zipline/dto/user/UserResponseDTO.java
  apiserver/domain/src/main/java/com/zipline/entity/user/User.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/UserRepository.java
  apiserver/service/src/main/java/com/zipline/service/user/UserService.java
  apiserver/service/src/main/java/com/zipline/service/user/UserServiceImpl.java
Labels: ✨ Feat

#179 refactor: 회원 관련 기능 정리 및 리팩터링
  apiserver/controller/src/main/java/com/zipline/controller/user/UserController.java
  apiserver/domain/src/main/java/com/zipline/dto/user/FindUserIdRequestDTO.java
  apiserver/domain/src/main/java/com/zipline/dto/user/LoginRequestDTO.java
  apiserver/domain/src/main/java/com/zipline/dto/user/SignUpRequestDTO.java
  apiserver/domain/src/main/java/com/zipline/dto/user/UserModifyRequestDTO.java
  apiserver/domain/src/main/java/com/zipline/dto/user/UserRequestDTO.java
  apiserver/domain/src/main/java/com/zipline/dto/user/UserResponseDTO.java
  apiserver/domain/src/main/java/com/zipline/entity/user/User.java
  apiserver/service/src/main/java/com/zipline/service/user/UserService.java
  apiserver/service/src/main/java/com/zipline/service/user/UserServiceImpl.java
Labels: ⚙️ Refactor

#176 feat: 문자 발송 기능 추가
  apiserver/common/src/main/java/com/zipline/global/config/SmsWebClientConfig.java
  apiserver/common/src/main/java/com/zipline/global/exception/custom/message/MessageCommonException.java
  apiserver/common/src/main/java/com/zipline/global/util/SmsSignatureGenerator.java
  apiserver/controller/build.gradle
  apiserver/controller/src/main/java/com/zipline/controller/message/MessageController.java
  apiserver/domain/src/main/java/com/zipline/dto/message/SendMessageRequestDTO.java
  apiserver/service/build.gradle
  apiserver/service/src/main/java/com/zipline/service/message/MessageService.java
  apiserver/service/src/main/java/com/zipline/service/message/MessageServiceImpl.java
  common/api/src/main/java/com/zipline/global/exception/custom/message/MessageCommonException.java
Labels: ✨ Feat

#185 fix: 설문 생성 시 Validation 버그 수정
  apiserver/service/src/main/java/com/zipline/service/survey/dto/request/QuestionValidator.java
  apiserver/service/src/main/java/com/zipline/service/survey/dto/request/SurveyCreateRequestDTO.java
Labels: 🛠️ Fix, ⚙️ Refactor

#187 (fix)부모 저장로직
  crawlerserver/service/src/main/java/com/zipline/service/publicItem/RegionCodeServiceImpl.java
Labels: 🛠️ Fix

#188 feat: 비밀번호 찾기 기능 추가
  apiserver/common/src/main/java/com/zipline/global/config/SecurityConfig.java
  apiserver/common/src/main/java/com/zipline/global/exception/custom/user/PasswordAnswerNotFoundException.java
  apiserver/common/src/main/java/com/zipline/global/exception/custom/user/PasswordQuestionNotFoundException.java
  apiserver/common/src/main/java/com/zipline/global/exception/custom/user/UserNotFoundException.java
  apiserver/controller/src/main/java/com/zipline/controller/user/UserController.java
  apiserver/controller/src/main/resources/application-dev.yml
  apiserver/domain/src/main/java/com/zipline/entity/user/PasswordQuestion.java
  apiserver/domain/src/main/java/com/zipline/entity/user/PasswordQuestionAnswer.java
  apiserver/domain/src/main/java/com/zipline/entity/user/User.java
  apiserver/domain/src/main/resources/data.sql
  apiserver/infrastructure/src/main/java/com/zipline/repository/user/PasswordQuestionAnswerRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/user/PasswordQuestionRepository.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/AgentPropertyServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/contract/ContractServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/counsel/CounselServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/customer/CustomerServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/survey/SurveyServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/user/UserService.java
  apiserver/service/src/main/java/com/zipline/service/user/UserServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/user/dto/request/FindPasswordRequestDTO.java
  apiserver/service/src/main/java/com/zipline/service/user/dto/request/ResetPasswordRequestDTO.java
  apiserver/service/src/main/java/com/zipline/service/user/dto/request/SignUpRequestDTO.java
Labels: ✨ Feat

#194 refactor: user api method 및 endpoint 수정
  apiserver/common/src/main/java/com/zipline/global/config/SecurityConfig.java
  apiserver/controller/src/main/java/com/zipline/controller/user/UserController.java
Labels: ⚙️ Refactor

#183 feat: 문자 템플릿 추가
  apiserver/common/src/main/java/com/zipline/global/exception/custom/message/MessageTemplateDuplicatedException.java
  apiserver/controller/src/main/java/com/zipline/controller/message/MessageController.java
  apiserver/controller/src/main/java/com/zipline/controller/message/MessageTemplateController.java
  apiserver/domain/src/main/java/com/zipline/entity/enums/MessageTemplateCategory.java
  apiserver/domain/src/main/java/com/zipline/entity/message/MessageTemplate.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/message/MessageTemplateRepository.java
  apiserver/service/src/main/java/com/zipline/service/message/MessageService.java
  apiserver/service/src/main/java/com/zipline/service/message/MessageServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/message/MessageTemplateService.java
  apiserver/service/src/main/java/com/zipline/service/message/MessageTemplateServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/message/dto/message/request/MessageTemplateRequestDTO.java
  apiserver/service/src/main/java/com/zipline/service/message/dto/message/request/SendMessageRequestDTO.java
  common/api/src/main/java/com/zipline/global/exception/custom/message/MessageCommonException.java
Labels: ✨ Feat

#200 feat: 라벨 생성
  apiserver/common/src/main/java/com/zipline/global/exception/label/LabelException.java
  apiserver/common/src/main/java/com/zipline/global/exception/label/errorcode/LabelErrorCode.java
  apiserver/controller/src/main/java/com/zipline/controller/label/LabelController.java
  apiserver/domain/src/main/java/com/zipline/entity/label/Label.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/label/LabelRepository.java
  apiserver/service/src/main/java/com/zipline/service/label/LabelService.java
  apiserver/service/src/main/java/com/zipline/service/label/LabelServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/label/dto/request/LabelRequestDTO.java
Labels: ✨ Feat

#195 (feat) 설문 생성 시 URL에 대체키를 사용하도록 변경
  apiserver/common/build.gradle
  apiserver/common/src/main/java/com/zipline/global/util/ULIDGenerator.java
  apiserver/controller/src/main/java/com/zipline/ApiServerApplication.java
  apiserver/controller/src/main/java/com/zipline/controller/survey/SurveyController.java
  apiserver/domain/src/main/java/com/zipline/entity/enums/SurveyStatus.java
  apiserver/domain/src/main/java/com/zipline/entity/survey/Survey.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/survey/SurveyRepository.java
  apiserver/service/src/main/java/com/zipline/service/survey/SurveyService.java
  apiserver/service/src/main/java/com/zipline/service/survey/SurveyServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/survey/dto/response/SurveyResponseDTO.java
Labels: ⚙️ Refactor, ✨ Feat

#205 feat: 고객 상세 조회 수정 - 계약, 매물, 상담 내역 조회
  apiserver/infrastructure/src/main/java/com/zipline/repository/customer/CustomerRepository.java
  apiserver/service/src/main/java/com/zipline/service/customer/CustomerServiceImpl.java
Labels: ✨ Feat

#206 feat: 라벨 수정
  apiserver/common/src/main/java/com/zipline/global/exception/label/errorcode/LabelErrorCode.java
  apiserver/controller/src/main/java/com/zipline/controller/label/LabelController.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/label/LabelRepository.java
  apiserver/service/src/main/java/com/zipline/service/label/LabelService.java
  apiserver/service/src/main/java/com/zipline/service/label/LabelServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/label/dto/response/LabelResponseDTO.java
Labels: ✨ Feat

#211 feat: 라벨 삭제
  apiserver/controller/src/main/java/com/zipline/controller/label/LabelController.java
  apiserver/domain/src/main/java/com/zipline/entity/label/Label.java
  apiserver/domain/src/main/java/com/zipline/entity/user/User.java
  apiserver/service/src/main/java/com/zipline/service/label/LabelService.java
  apiserver/service/src/main/java/com/zipline/service/label/LabelServiceImpl.java
Labels: ✨ Feat

#213 feat: 라벨 리스트 조회
  apiserver/controller/src/main/java/com/zipline/controller/label/LabelController.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/label/LabelRepository.java
  apiserver/service/src/main/java/com/zipline/service/label/LabelService.java
  apiserver/service/src/main/java/com/zipline/service/label/LabelServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/label/dto/response/LabelListResponseDTO.java
Labels: ✨ Feat

#212 feat: Counsel Type, DueDate 추가
  apiserver/common/src/main/java/com/zipline/global/exception/counsel/errorcode/CounselErrorCode.java
  apiserver/controller/src/main/java/com/zipline/controller/counsel/CounselController.java
  apiserver/controller/src/main/java/com/zipline/controller/customer/CustomerController.java
  apiserver/domain/src/main/java/com/zipline/entity/counsel/Counsel.java
  apiserver/domain/src/main/java/com/zipline/entity/enums/CounselType.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/agentProperty/AgentPropertyRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/counsel/CounselRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/customer/CustomerRepository.java
  apiserver/service/src/main/java/com/zipline/service/counsel/CounselService.java
  apiserver/service/src/main/java/com/zipline/service/counsel/CounselServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/counsel/dto/request/CounselCreateRequestDTO.java
  apiserver/service/src/main/java/com/zipline/service/counsel/dto/request/CounselModifyRequestDTO.java
  apiserver/service/src/main/java/com/zipline/service/counsel/dto/response/CounselListResponseDTO.java
  apiserver/service/src/main/java/com/zipline/service/counsel/dto/response/CounselResponseDTO.java
  apiserver/service/src/main/java/com/zipline/service/customer/CustomerServiceImpl.java
Labels: ✨ Feat

#217 feat: 고객 등록 시 라벨 등록
  apiserver/domain/src/main/java/com/zipline/entity/customer/Customer.java
  apiserver/domain/src/main/java/com/zipline/entity/label/Label.java
  apiserver/domain/src/main/java/com/zipline/entity/label/LabelCustomer.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/label/LabelCustomerRepository.java
  apiserver/service/src/main/java/com/zipline/service/customer/CustomerServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/customer/dto/request/CustomerRegisterRequestDTO.java
Labels: ✨ Feat

#218 fix: 에러처리 버그 수정
  apiserver/service/src/main/java/com/zipline/service/label/LabelServiceImpl.java
Labels: 🛠️ Fix

#214 feat: Region 조회기능
  apiserver/common/src/main/java/com/zipline/global/config/RedisCacheConfig.java
  apiserver/common/src/main/java/com/zipline/global/config/RedisConfig.java
  apiserver/common/src/main/java/com/zipline/global/exception/custom/region/RegionException.java
  apiserver/common/src/main/java/com/zipline/global/exception/custom/region/errorcode/RegionErrorCode.java
  apiserver/common/src/main/java/com/zipline/global/response/ApiResponse.java
  apiserver/controller/src/main/java/com/zipline/controller/region/RegionController.java
  apiserver/controller/src/main/resources/application-dev.yml
  apiserver/domain/src/main/java/com/zipline/entity/enums/CrawlStatus.java
  apiserver/domain/src/main/java/com/zipline/entity/publicitem/Region.java
  apiserver/entity/publicitem/Region.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/contract/ContractRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/region/RegionRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/survey/SurveyRepository.java
  apiserver/service/src/main/java/com/zipline/service/region/RegionService.java
  apiserver/service/src/main/java/com/zipline/service/region/RegionServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/region/dto/FlatRegionDTO.java
  crawlerserver/infrastructure/src/main/java/com/zipline/infrastructure/publicItem/repository/RegionRepository.java
  docs/README.md
  docs/troubleshoot/2025-04-07_NaverCrawlFix.md
  docs/troubleshoot/2025-04-09_ci_cd_sh_special_letter_issue.md
  docs/troubleshoot/2025-04-25_RedisError.md
Labels: ✨ Feat

#223 feat: 대한민국 지역코드 추가기능과 리펙토링
  crawlerserver/domain/src/main/java/com/zipline/domain/dto/publicitem/RegionDTO.java
  crawlerserver/service/src/main/java/com/zipline/service/publicItem/RegionCodeServiceImpl.java
Labels: ✨ Feat

#232 hotfix: 타입 에러 수정
  apiserver/controller/src/main/java/com/zipline/controller/user/UserController.java
  apiserver/service/src/main/java/com/zipline/service/user/dto/request/LoginRequestDTO.java
  apiserver/service/src/main/java/com/zipline/service/user/dto/request/SignUpRequestDTO.java
Labels: 🔥 HotFix

#202 feat: 문자 발송 내역 조회 api 추가
  apiserver/common/src/main/java/com/zipline/global/config/SmsWebClientConfig.java
  apiserver/common/src/main/java/com/zipline/global/exception/message/errorcode/MessageErrorCode.java
  apiserver/common/src/main/java/com/zipline/global/util/SmsSignatureGenerator.java
  apiserver/controller/src/main/java/com/zipline/controller/message/MessageController.java
  apiserver/controller/src/main/java/com/zipline/controller/message/MessageTemplateController.java
  apiserver/domain/src/main/java/com/zipline/entity/message/MessageHistory.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/message/MessageHistoryRepository.java
  apiserver/service/src/main/java/com/zipline/service/message/MessageHistoryParamFormatter.java
  apiserver/service/src/main/java/com/zipline/service/message/MessageService.java
  apiserver/service/src/main/java/com/zipline/service/message/MessageServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/message/MessageTemplateService.java
  apiserver/service/src/main/java/com/zipline/service/message/MessageTemplateServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/message/dto/request/MessageHistoryRequestDTO.java
  apiserver/service/src/main/java/com/zipline/service/message/dto/request/MessageTemplateRequestDTO.java
  apiserver/service/src/main/java/com/zipline/service/message/dto/request/SendMessageRequestDTO.java
  apiserver/service/src/main/java/com/zipline/service/message/dto/response/MessageHistoryDetailDTO.java
  apiserver/service/src/main/java/com/zipline/service/message/dto/response/MessageHistoryResponseDTO.java
Labels: ✨ Feat

#224 feat: 문자 템플릿 목록 조회
  apiserver/controller/bin/main/com/zipline/controller/message/MessageTemplateController.class
  apiserver/controller/src/main/java/com/zipline/controller/message/MessageTemplateController.java
  apiserver/domain/src/main/java/com/zipline/entity/message/MessageTemplate.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/message/MessageTemplateRepository.java
  apiserver/service/src/main/java/com/zipline/service/message/MessageTemplateService.java
  apiserver/service/src/main/java/com/zipline/service/message/MessageTemplateServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/message/dto/message/response/MessageTemplateResponseDTO.java
Labels: ✨ Feat

#220 feat: 고객 수정 시 라벨 수정
  apiserver/domain/src/main/java/com/zipline/entity/customer/Customer.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/label/LabelCustomerRepository.java
  apiserver/service/src/main/java/com/zipline/service/customer/CustomerServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/customer/dto/request/CustomerModifyRequestDTO.java
  apiserver/service/src/main/java/com/zipline/service/customer/dto/response/CustomerDetailResponseDTO.java
Labels: ✨ Feat

#234 refactor: Customer
  apiserver/controller/src/main/java/com/zipline/controller/customer/CustomerController.java
  apiserver/domain/src/main/java/com/zipline/entity/label/LabelCustomer.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/label/LabelRepository.java
  apiserver/service/src/main/java/com/zipline/service/customer/CustomerService.java
  apiserver/service/src/main/java/com/zipline/service/customer/CustomerServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/customer/dto/request/CustomerModifyRequestDTO.java
  apiserver/service/src/main/java/com/zipline/service/customer/dto/request/CustomerRegisterRequestDTO.java
Labels: ⚙️ Refactor

#235 feat: 문자 템플릿 삭제
  apiserver/common/src/main/java/com/zipline/global/exception/message/errorcode/MessageTemplateErrorCode.java
  apiserver/controller/src/main/java/com/zipline/controller/message/MessageTemplateController.java
  apiserver/domain/src/main/java/com/zipline/entity/message/MessageTemplate.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/message/MessageTemplateRepository.java
  apiserver/service/src/main/java/com/zipline/service/message/MessageTemplateService.java
  apiserver/service/src/main/java/com/zipline/service/message/MessageTemplateServiceImpl.java
Labels: ✨ Feat

#237 feat: 문자 템플릿 수정
  apiserver/common/src/main/java/com/zipline/global/exception/message/errorcode/MessageTemplateErrorCode.java
  apiserver/controller/src/main/java/com/zipline/controller/message/MessageTemplateController.java
  apiserver/domain/src/main/java/com/zipline/entity/message/MessageTemplate.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/message/MessageTemplateRepository.java
  apiserver/service/src/main/java/com/zipline/service/message/MessageTemplateService.java
  apiserver/service/src/main/java/com/zipline/service/message/MessageTemplateServiceImpl.java
Labels: ✨ Feat

#236 refactor: Survey Api
  apiserver/controller/src/main/java/com/zipline/controller/survey/SurveyController.java
  apiserver/service/src/main/java/com/zipline/service/survey/SurveyService.java
  apiserver/service/src/main/java/com/zipline/service/survey/SurveyServiceImpl.java
Labels: ⚙️ Refactor

#238 feat: 고객 조회 시 라벨 조회
  apiserver/domain/src/main/java/com/zipline/entity/customer/Customer.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/customer/CustomerRepository.java
  apiserver/service/src/main/java/com/zipline/service/customer/CustomerServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/customer/dto/response/CustomerListResponseDTO.java
Labels: ✨ Feat

#241 feat: 일정 생성 api 추가
  apiserver/common/src/main/java/com/zipline/global/exception/schedule/ScheduleException.java
  apiserver/common/src/main/java/com/zipline/global/exception/schedule/errorcode/ScheduleErrorCode.java
  apiserver/controller/src/main/java/com/zipline/controller/schedule/ScheduleController.java
  apiserver/domain/src/main/java/com/zipline/entity/schedule/Schedule.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/schedule/ScheduleRepository.java
  apiserver/service/build.gradle
  apiserver/service/src/main/java/com/zipline/service/schedule/ScheduleService.java
  apiserver/service/src/main/java/com/zipline/service/schedule/ScheduleServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/schedule/dto/request/ScheduleCreateRequestDTO.java
Labels: ✨ Feat

#245 refactor: 매물 리펙토링
  apiserver/common/src/main/java/com/zipline/global/config/JacksonConfig.java
  apiserver/controller/src/main/java/com/zipline/controller/agentProperty/AgentPropertyController.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/agentProperty/AgentPropertyRepository.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/AgentPropertyServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/dto/request/AgentPropertyRequestDTO.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/dto/response/AgentPropertyListResponseDTO.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/dto/response/AgentPropertyResponseDTO.java
Labels: 🛠️ Fix, ⚙️ Refactor

#250 feat: 일정 삭제 api 추가
  apiserver/common/src/main/java/com/zipline/global/exception/schedule/errorcode/ScheduleErrorCode.java
  apiserver/controller/src/main/java/com/zipline/controller/schedule/ScheduleController.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/schedule/ScheduleRepository.java
  apiserver/service/src/main/java/com/zipline/service/schedule/ScheduleService.java
  apiserver/service/src/main/java/com/zipline/service/schedule/ScheduleServiceImpl.java
Labels: ✨ Feat

#243 refactor: 공개매물view api 서버로 이전 리펙터링
  apiserver/common/src/main/java/com/zipline/global/exception/publicitem/PublicItemException.java
  apiserver/common/src/main/java/com/zipline/global/exception/publicitem/errorcode/PublicItemErrorCode.java
  apiserver/controller/src/main/java/com/zipline/controller/publicitem/PropertyArticleViewController.java
  apiserver/domain/src/main/java/com/zipline/entity/publicitem/PropertyArticle.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/publicitem/PropertyArticleViewRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/publicitem/PropertyArticleViewSpecification.java
  apiserver/service/src/main/java/com/zipline/service/publicitem/PropertyArticleViewService.java
  apiserver/service/src/main/java/com/zipline/service/publicitem/PropertyArticleViewServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/publicitem/dto/PropertyArticlePageResponseDTO.java
  apiserver/service/src/main/java/com/zipline/service/publicitem/dto/PropertyArticleSearchDTO.java
  apiserver/service/src/main/java/com/zipline/service/publicitem/dto/PropertyArticleViewDTO.java
  apiserver/service/src/main/java/com/zipline/service/publicitem/spec/PropertyArticleSpecificationBuilder.java
  crawlerserver/common/src/main/java/com/zipline/global/exception/custom/publicItem/InvalidPropertySearchException.java
  crawlerserver/controller/src/main/java/com/zipline/controller/publicitem/NaverMigrationController.java
  crawlerserver/domain/src/main/java/com/zipline/domain/dto/publicitem/PropertyArticleSearchDTO.java
  crawlerserver/infrastructure/src/main/java/com/zipline/infrastructure/publicItem/repository/PropertyArticleViewRepository.java
  crawlerserver/service/src/main/java/com/zipline/service/publicItem/PropertyArticleViewServiceimpl.java
Labels: ✨ Feat

#247 feat: 통계 API
  apiserver/controller/src/main/java/com/zipline/controller/statics/StaticsController.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/contract/ContractRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/survey/SurveyRepository.java
  apiserver/service/src/main/java/com/zipline/service/statics/StaticsService.java
  apiserver/service/src/main/java/com/zipline/service/statics/StaticsServiceImpl.java
Labels: ✨ Feat

#252 feat: 일정 조회 api 추가
  apiserver/common/src/main/java/com/zipline/global/config/JacksonConfig.java
  apiserver/controller/src/main/java/com/zipline/controller/schedule/ScheduleController.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/schedule/ScheduleRepository.java
  apiserver/service/src/main/java/com/zipline/service/schedule/ScheduleService.java
  apiserver/service/src/main/java/com/zipline/service/schedule/ScheduleServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/schedule/dto/request/DateRangeRequest.java
  apiserver/service/src/main/java/com/zipline/service/schedule/dto/response/ScheduleResponseDTO.java
Labels: ✨ Feat

#263 feat: PageResponseDTO에 정렬 추가
  apiserver/common/src/main/java/com/zipline/global/exception/page/PagingException.java
  apiserver/common/src/main/java/com/zipline/global/exception/page/errorcode/PagingErrorCode.java
  apiserver/common/src/main/java/com/zipline/global/request/PageRequestDTO.java
  apiserver/common/src/main/java/com/zipline/global/request/PageRequestDTOBinder.java
Labels: ✨ Feat

#265 refactor: 계약 리펙토링
  apiserver/common/src/main/java/com/zipline/global/exception/contract/errorcode/ContractErrorCode.java
  apiserver/controller/src/main/java/com/zipline/controller/contract/ContractController.java
  apiserver/domain/src/main/java/com/zipline/entity/contract/ContractDocument.java
  apiserver/domain/src/main/java/com/zipline/entity/contract/CustomerContract.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/contract/ContractDocumentRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/contract/ContractRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/contract/CustomerContractRepository.java
  apiserver/service/src/main/java/com/zipline/service/contract/ContractServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/contract/dto/request/ContractRequestDTO.java
  apiserver/service/src/main/java/com/zipline/service/contract/dto/response/ContractListResponseDTO.java
  apiserver/service/src/main/java/com/zipline/service/contract/dto/response/ContractResponseDTO.java
  apiserver/service/src/main/java/com/zipline/service/customer/CustomerServiceImpl.java
Labels: ⚙️ Refactor

#255 feat: 매물 목록 조회 시 필터링
  apiserver/common/src/main/java/com/zipline/global/exception/agentProperty/errorcode/PropertyErrorCode.java
  apiserver/common/src/main/java/com/zipline/global/request/AgentPropertyFilterRequestDTO.java
  apiserver/controller/src/main/java/com/zipline/controller/agentProperty/AgentPropertyController.java
  apiserver/domain/build.gradle
  apiserver/infrastructure/src/main/java/com/zipline/repository/agentProperty/AgentPropertyQueryRepository.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/AgentPropertyService.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/AgentPropertyServiceImpl.java
Labels: ✨ Feat

#262 feat: 일정 수정 api 추가
  apiserver/controller/src/main/java/com/zipline/controller/schedule/ScheduleController.java
  apiserver/domain/src/main/java/com/zipline/entity/schedule/Schedule.java
  apiserver/service/src/main/java/com/zipline/service/schedule/ScheduleFieldUpdateProcessor.java
  apiserver/service/src/main/java/com/zipline/service/schedule/ScheduleService.java
  apiserver/service/src/main/java/com/zipline/service/schedule/ScheduleServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/schedule/dto/request/ScheduleCreateRequestDTO.java
  apiserver/service/src/main/java/com/zipline/service/schedule/dto/request/ScheduleModifyRequestDTO.java
Labels: ✨ Feat

#271 feat: 계약 삭제
  apiserver/controller/src/main/java/com/zipline/controller/contract/ContractController.java
  apiserver/service/src/main/java/com/zipline/service/contract/ContractService.java
  apiserver/service/src/main/java/com/zipline/service/contract/ContractServiceImpl.java
Labels: ✨ Feat

#276 feat: 계약-매물 연결
  apiserver/common/src/main/java/com/zipline/global/exception/contract/errorcode/ContractErrorCode.java
  apiserver/domain/src/main/java/com/zipline/entity/contract/Contract.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/AgentPropertyServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/dto/request/AgentPropertyRequestDTO.java
  apiserver/service/src/main/java/com/zipline/service/contract/ContractServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/contract/dto/request/ContractRequestDTO.java
  apiserver/service/src/main/java/com/zipline/service/contract/dto/response/ContractListResponseDTO.java
  apiserver/service/src/main/java/com/zipline/service/contract/dto/response/ContractResponseDTO.java
Labels: ✨ Feat

#278 feat: 계약 필터링
  apiserver/common/src/main/java/com/zipline/global/request/ContractFilterRequestDTO.java
  apiserver/controller/src/main/java/com/zipline/controller/contract/ContractController.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/contract/ContractQueryRepository.java
  apiserver/service/src/main/java/com/zipline/service/contract/ContractService.java
  apiserver/service/src/main/java/com/zipline/service/contract/ContractServiceImpl.java
Labels: ✨ Feat

#280 fix: 통계컨트롤러의 타입이 수정 되어 있지 않았던 문제를 수정했습니다.
  apiserver/controller/src/main/java/com/zipline/controller/statics/StaticsController.java
Labels: ✨ Feat

#281 feat: 고객 목록 필터링
  apiserver/common/src/main/java/com/zipline/global/request/CustomerFilterRequestDTO.java
  apiserver/controller/src/main/java/com/zipline/controller/customer/CustomerController.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/customer/CustomerRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/customer/QCustomerRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/customer/QCustomerRepositoryImpl.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/region/RegionRepository.java
  apiserver/service/src/main/java/com/zipline/service/customer/CustomerService.java
  apiserver/service/src/main/java/com/zipline/service/customer/CustomerServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/customer/dto/response/CustomerDetailResponseDTO.java
Labels: ✨ Feat

#287 feat: 대시보드 - 상담 목록 조회
  apiserver/controller/src/main/java/com/zipline/controller/counsel/CounselController.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/counsel/QCounselRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/counsel/QCounselRepositoryImpl.java
  apiserver/service/src/main/java/com/zipline/service/counsel/CounselService.java
  apiserver/service/src/main/java/com/zipline/service/counsel/CounselServiceImpl.java
Labels: ✨ Feat

#293 (fix)공개매물view api 관련 문제 수정
  apiserver/common/src/main/java/com/zipline/global/exception/publicitem/errorcode/PublicItemErrorCode.java
  apiserver/controller/bin/main/com/zipline/controller/message/MessageTemplateController.class
  apiserver/controller/src/main/java/com/zipline/controller/region/RegionController.java
  apiserver/domain/src/main/java/com/zipline/entity/publicitem/PropertyArticle.java
  apiserver/entity/publicitem/Region.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/publicitem/PropertyArticleViewSpecification.java
  apiserver/service/src/main/java/com/zipline/service/publicitem/PropertyArticleViewServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/publicitem/dto/PropertyArticleSearchDTO.java
  apiserver/service/src/main/java/com/zipline/service/publicitem/dto/PropertyArticleViewDTO.java
  apiserver/service/src/main/java/com/zipline/service/publicitem/spec/PropertyArticleSpecificationBuilder.java
Labels: 🛠️ Fix, ✨ Feat
