Repository Kernel360/Kernel360-KDEV4-ZIPLINE, pull requests merged in 2025-05, with the labels that each got.

#297 (fix) 매물 필터링 유효성 검증
  apiserver/common/src/main/java/com/zipline/global/request/AgentPropertyFilterRequestDTO.java
  apiserver/controller/src/main/java/com/zipline/controller/agentProperty/AgentPropertyController.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/AgentPropertyServiceImpl.java
Labels: 🛠️ Fix

#301 fix: 계약 등록/수정 시 임대/매도, 임차/매수 고객이 같은 경우 에러처리
  apiserver/common/src/main/java/com/zipline/global/exception/contract/errorcode/ContractErrorCode.java
  apiserver/service/src/main/java/com/zipline/service/contract/ContractServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/contract/dto/request/ContractRequestDTO.java
Labels: 🛠️ Fix

#302 feat: 목록 조회 시 검색 필터링 추가
  apiserver/common/src/main/java/com/zipline/global/request/ContractFilterRequestDTO.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/contract/ContractQueryRepository.java
Labels: ✨ Feat

#310 fix: 계약 검색 시 keyword 하나로 받아 OR로 비교
  apiserver/infrastructure/src/main/java/com/zipline/repository/contract/ContractQueryRepository.java
Labels: 🛠️ Fix

#308 (refactor)지역 오류 코드 패키지 경로수정
  apiserver/common/src/main/java/com/zipline/global/exception/region/RegionException.java
  apiserver/common/src/main/java/com/zipline/global/exception/region/errorcode/RegionErrorCode.java
  apiserver/service/src/main/java/com/zipline/service/region/RegionServiceImpl.java
Labels: 🛠️ Fix, ✨ Feat

#319 feat: 상담 목록 조회 필터링 조건 추가
  apiserver/common/src/main/java/com/zipline/global/request/CounselFilterRequestDTO.java
  apiserver/domain/src/main/java/com/zipline/entity/enums/CounselType.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/counsel/QCounselRepositoryImpl.java
  apiserver/service/src/main/java/com/zipline/service/counsel/CounselServiceImpl.java
Labels: ✨ Feat

#314 feat: 정렬 기능 추가
  apiserver/common/src/main/java/com/zipline/global/request/ContractFilterRequestDTO.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/contract/ContractQueryRepository.java
Labels: ✨ Feat

#316 fix: 계약 문서 수정 시 버그 해결
  apiserver/controller/src/main/java/com/zipline/controller/contract/ContractController.java
  apiserver/domain/src/main/java/com/zipline/entity/contract/Contract.java
  apiserver/service/src/main/java/com/zipline/service/contract/ContractService.java
  apiserver/service/src/main/java/com/zipline/service/contract/ContractServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/contract/dto/response/ContractResponseDTO.java
Labels: 🛠️ Fix

#325 fix: 계약 카테고리 등록 및 수정 시 입력 버그 수정
  apiserver/service/src/main/java/com/zipline/service/contract/ContractServiceImpl.java
Labels: 🛠️ Fix

#321 feat: 상담 상세 조회 반환 값 추가
  apiserver/service/src/main/java/com/zipline/service/counsel/CounselServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/counsel/dto/response/CounselResponseDTO.java
Labels: ✨ Feat

#327 feat: 매물 - 상담 히스토리 조회
  apiserver/controller/src/main/java/com/zipline/controller/agentProperty/AgentPropertyController.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/counsel/CounselRepository.java
  apiserver/service/src/main/java/com/zipline/service/counsel/CounselService.java
  apiserver/service/src/main/java/com/zipline/service/counsel/CounselServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/counsel/dto/response/CounselHistoryResponseDTO.java
Labels: ✨ Feat

#330 fix: 계약 수정 시 응답 데이터 버그
  apiserver/domain/src/main/java/com/zipline/entity/contract/CustomerContract.java
  apiserver/service/src/main/java/com/zipline/service/contract/ContractServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/contract/dto/response/ContractResponseDTO.java
Labels: 🛠️ Fix

#337 fix: 매물 생성 및 수정시 버그
  apiserver/common/src/main/java/com/zipline/global/exception/agentProperty/errorcode/PropertyErrorCode.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/AgentPropertyServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/dto/request/AgentPropertyRequestDTO.java
Labels: 🛠️ Fix

#333 feat: 계약 만료 문자 자동 발송 기능 추가
  apiserver/common/src/main/java/com/zipline/global/exception/message/errorcode/MessageErrorCode.java
  apiserver/controller/src/main/java/com/zipline/ApiServerApplication.java
  apiserver/controller/src/main/java/com/zipline/controller/message/MessageTemplateController.java
  apiserver/domain/src/main/java/com/zipline/entity/contract/Contract.java
  apiserver/domain/src/main/java/com/zipline/entity/enums/MessageTemplateVariables.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/contract/ContractRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/user/UserRepository.java
  apiserver/service/src/main/java/com/zipline/service/message/MessageTemplateService.java
  apiserver/service/src/main/java/com/zipline/service/message/MessageTemplateServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/message/NotificationMessageService.java
  apiserver/service/src/main/java/com/zipline/service/message/NotificationMessageServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/message/dto/request/NotificationMessageDTO.java
  apiserver/service/src/main/java/com/zipline/service/message/dto/response/MessageTemplateResponseDTO.java
Labels: ✨ Feat

#339 feat: detailAddress 컬럼 추가
  apiserver/domain/src/main/java/com/zipline/entity/agentProperty/AgentProperty.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/AgentPropertyServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/dto/request/AgentPropertyRequestDTO.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/dto/response/AgentPropertyListResponseDTO.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/dto/response/AgentPropertyResponseDTO.java
Labels: ✨ Feat

#342 fix: 누락한 자동 문자 발신 번호 환경변수 추가
  apiserver/controller/src/main/resources/application-dev.yml
  apiserver/controller/src/main/resources/application-test.yml
Labels: 🧹 Chore, 🛠️ Fix

#343 fix: 매물-계약 조회 시 버그 수정
  apiserver/domain/src/main/java/com/zipline/entity/contract/Contract.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/contract/ContractRepository.java
  apiserver/service/src/main/java/com/zipline/service/contract/ContractServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/contract/dto/response/ContractPropertyResponseDTO.java
Labels: 🛠️ Fix

#347 (cicd)배포설정 수정
  .github/workflows/cicd-dev.yml
Labels: 🤖 CI/CD

#336 feat: 생일 축하 문자 자동 발송 기능 추가
  apiserver/common/src/main/java/com/zipline/global/exception/message/errorcode/MessageErrorCode.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/customer/CustomerRepository.java
  apiserver/service/src/main/java/com/zipline/service/message/NotificationMessageServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/message/dto/request/BirthdayNotificationMessageDTO.java
  apiserver/service/src/main/java/com/zipline/service/message/dto/request/ExpiredNotificationMessageDTO.java
  apiserver/service/src/main/java/com/zipline/service/message/dto/request/NotificationMessage.java
Labels: ✨ Feat

#358 fix: 매물 버그 수정
  apiserver/domain/src/main/java/com/zipline/entity/agentProperty/AgentProperty.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/agentProperty/AgentPropertyQueryRepository.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/dto/request/AgentPropertyRequestDTO.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/dto/response/AgentPropertyListResponseDTO.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/dto/response/AgentPropertyResponseDTO.java
  apiserver/service/src/main/java/com/zipline/service/counsel/dto/response/CounselResponseDTO.java
Labels: 🛠️ Fix

#359 feat: 계약 - 고객 리스트로 받도록 수정
  apiserver/controller/src/main/java/com/zipline/controller/contract/ContractController.java
  apiserver/service/src/main/java/com/zipline/service/contract/ContractServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/contract/dto/request/ContractRequestDTO.java
  apiserver/service/src/main/java/com/zipline/service/contract/dto/response/ContractListResponseDTO.java
  apiserver/service/src/main/java/com/zipline/service/contract/dto/response/ContractResponseDTO.java
Labels: 🛠️ Fix, ✨ Feat

#357 remove: 사용하지 않는 코드 제거
  crawlerserver/common/src/main/java/com/zipline/global/util/CrawlingStatusManager.java
  crawlerserver/common/src/main/java/com/zipline/global/util/CrawlingStatusUtil.java
  crawlerserver/controller/src/main/java/com/zipline/controller/naver/NaverRawArticleController.java
  crawlerserver/controller/src/main/java/com/zipline/controller/status/CrawlerController.java
  crawlerserver/domain/src/main/java/com/zipline/domain/entity/migration/Migration.java
  crawlerserver/domain/src/main/java/com/zipline/domain/entity/naver/NaverRawArticle.java
  crawlerserver/domain/src/main/java/com/zipline/domain/entity/publicitem/PropertyArticle.java
  crawlerserver/infrastructure/src/main/java/com/zipline/infrastructure/region/RegionRepository.java
  crawlerserver/service/src/main/java/com/zipline/service/migration/NaverMigrationService.java
  crawlerserver/service/src/main/java/com/zipline/service/migration/NaverMigrationServiceImpl.java
  crawlerserver/service/src/main/java/com/zipline/service/naver/NaverRawArticleService.java
  crawlerserver/service/src/main/java/com/zipline/service/naver/NaverRawArticleServiceImpl.java
  crawlerserver/service/src/main/java/com/zipline/service/naver/dto/PageResultDTO.java
  crawlerserver/service/src/main/java/com/zipline/service/region/RegionCodeServiceImpl.java
  crawlerserver/service/src/main/java/com/zipline/service/region/dto/RegionDTO.java
  crawlerserver/service/src/main/java/com/zipline/service/upload/ProxyListUploadServiceImpl.java
Labels: 🗑️ Remove

#366 fix: 최근 유입 고객 수 기준을 설문 응답 제출 수로 변경
  apiserver/infrastructure/src/main/java/com/zipline/repository/survey/SurveyAnswerRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/survey/SurveyRepository.java
  apiserver/service/src/main/java/com/zipline/service/statics/StaticsServiceImpl.java
Labels: 🛠️ Fix

#364 fix: 중복 생성 시 에러처리
  apiserver/common/src/main/java/com/zipline/global/exception/agentProperty/errorcode/PropertyErrorCode.java
  apiserver/common/src/main/java/com/zipline/global/exception/contract/errorcode/ContractErrorCode.java
  apiserver/common/src/main/java/com/zipline/global/request/AgentPropertyFilterRequestDTO.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/agentProperty/AgentPropertyRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/contract/ContractRepository.java
  apiserver/service/src/main/java/com/zipline/service/agentProperty/AgentPropertyServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/contract/ContractServiceImpl.java
Labels: 🛠️ Fix

#369 feat: 고객 상세 - 상담, 계약 리스트 페이지네이션 추가
  apiserver/controller/src/main/java/com/zipline/controller/customer/CustomerController.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/contract/CustomerContractRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/counsel/CounselRepository.java
  apiserver/service/src/main/java/com/zipline/service/customer/CustomerService.java
  apiserver/service/src/main/java/com/zipline/service/customer/CustomerServiceImpl.java
Labels: ✨ Feat

#371 feat: 엑셀 업로드 - 고객, 매물
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-test.yml
  apiserver/common/build.gradle
  apiserver/common/src/main/java/com/zipline/global/config/RestClientConfig.java
  apiserver/common/src/main/java/com/zipline/global/exception/GlobalExceptionHandler.java
  apiserver/common/src/main/java/com/zipline/global/exception/excel/ExcelException.java
  apiserver/common/src/main/java/com/zipline/global/exception/excel/errorcode/ExcelErrorCode.java
  apiserver/common/src/main/java/com/zipline/global/exception/external/ExternalException.java
  apiserver/common/src/main/java/com/zipline/global/exception/external/errorcode/ExternalErrorCode.java
  apiserver/common/src/main/java/com/zipline/global/response/ExceptionResponseDTO.java
  apiserver/common/src/main/java/com/zipline/global/util/ExcelParser.java
  apiserver/controller/src/main/java/com/zipline/controller/agentProperty/AgentPropertyController.java
  apiserver/controller/src/main/java/com/zipline/controller/customer/CustomerController.java
  apiserver/controller/src/main/resources/application-dev.yml
  apiserver/controller/src/main/resources/application-test.yml
  apiserver/domain/src/main/java/com/zipline/entity/customer/Customer.java
  apiserver/infrastructure/build.gradle
  apiserver/infrastructure/src/main/java/com/zipline/api/GeoCodeResultVO.java
  apiserver/infrastructure/src/main/java/com/zipline/api/KakaoGeoClient.java
  apiserver/infrastructure/src/main/java/com/zipline/api/KakaoGeocodeResponseDTO.java
  apiserver/infrastructure/src/main/java/com/zipline/excel/AgentPropertyExcelDTO.java
  apiserver/infrastructure/src/main/java/com/zipline/excel/AgentPropertyExcelRowMapper.java
  apiserver/infrastructure/src/main/java/com/zipline/excel/CustomerExcelDTO.java
  apiserver/infrastructure/src/main/java/com/zipline/excel/CustomerExcelRowMapper.java
  apiserver/infrastructure/src/main/java/com/zipline/excel/ExcelReader.java
  apiserver/infrastructure/src/main/java/com/zipline/excel/ExcelRowMapper.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/customer/CustomerRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/customer/QCustomerRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/customer/QCustomerRepositoryImpl.java
  apiserver/service/src/main/java/com/zipline/service/excel/ExcelService.java
  apiserver/service/src/main/java/com/zipline/service/excel/ExcelServiceImpl.java
Labels: 🧹 Chore, ✨ Feat, 🤖 CI/CD

#375 (feat)업데이트 기능 추가 + 배치 처리
  crawlerserver/domain/src/main/java/com/zipline/domain/entity/zigbang/ZigBangArticle.java
  crawlerserver/infrastructure/src/main/java/com/zipline/infrastructure/zigbang/ZigBangArticleRepository.java
  crawlerserver/service/src/main/java/com/zipline/service/zigbang/crawler/DefaultZigBangArticleCrawler.java
  crawlerserver/service/src/main/java/com/zipline/service/zigbang/crawler/SharedZigbangCrawler.java
Labels: ✨ Feat

#381 fix: 법정동 코드 필터링 시 LIKE로 검색
  apiserver/infrastructure/src/main/java/com/zipline/repository/customer/QCustomerRepositoryImpl.java
Labels: 🛠️ Fix

#387 fix: 공개매물 - 지역코드 필터링 like로 검색
  apiserver/infrastructure/src/main/java/com/zipline/repository/publicitem/PropertyArticleViewSpecification.java
Labels: 🛠️ Fix

#377 fix: 엑셀 업로드 - 주소 3-Depth 고정
  apiserver/infrastructure/src/main/java/com/zipline/api/KakaoGeocodeResponseDTO.java
  apiserver/infrastructure/src/main/java/com/zipline/excel/AgentPropertyExcelRowMapper.java
  apiserver/infrastructure/src/main/java/com/zipline/excel/ExcelReader.java
  apiserver/service/src/main/java/com/zipline/service/excel/ExcelServiceImpl.java
Labels: 🛠️ Fix

#392 fix : 엑셀 업로드 - 매물 주소 매핑
  apiserver/infrastructure/src/main/java/com/zipline/api/GeoCodeResultVO.java
  apiserver/infrastructure/src/main/java/com/zipline/api/KakaoGeocodeResponseDTO.java
  apiserver/service/src/main/java/com/zipline/service/excel/ExcelServiceImpl.java
Labels: 🛠️ Fix

#401 feat: 필터링 조건 추가
  apiserver/common/src/main/java/com/zipline/global/request/ContractFilterRequestDTO.java
  apiserver/controller/src/main/java/com/zipline/controller/user/UserController.java
  apiserver/domain/src/main/java/com/zipline/entity/enums/ContractStatus.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/contract/ContractQueryRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/contract/ContractRepository.java
  apiserver/service/src/main/java/com/zipline/service/statics/StaticsServiceImpl.java
Labels: ✨ Feat

#379 fix: 문자 템플릿 카테고리 수정 적용 안 되는 버그 수정
  apiserver/domain/src/main/java/com/zipline/entity/message/MessageTemplate.java
  apiserver/service/src/main/java/com/zipline/service/message/MessageTemplateServiceImpl.java
Labels: 🛠️ Fix

#390 (fix) 고객 등록, 수정 시 중복된 고객 정보인지 체크하는 로직 추가
  apiserver/common/src/main/java/com/zipline/global/exception/customer/errorcode/CustomerErrorCode.java
  apiserver/domain/src/main/java/com/zipline/entity/customer/Customer.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/customer/CustomerRepository.java
  apiserver/infrastructure/src/main/java/com/zipline/repository/customer/QCustomerRepositoryImpl.java
  apiserver/service/src/main/java/com/zipline/service/customer/CustomerServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/customer/dto/request/CustomerModifyRequestDTO.java
  apiserver/service/src/main/java/com/zipline/service/customer/dto/request/CustomerRegisterRequestDTO.java
Labels: 🛠️ Fix

#398 fix: 중복로그인 허용
  apiserver/common/src/main/java/com/zipline/global/jwt/TokenProvider.java
  apiserver/controller/src/main/java/com/zipline/controller/user/UserController.java
  apiserver/service/src/main/java/com/zipline/service/user/UserService.java
  apiserver/service/src/main/java/com/zipline/service/user/UserServiceImpl.java
Labels: 🛠️ Fix

#396 fix: 일정 생성 시 description optional하게 받을 수 있도록 수정
  apiserver/controller/bin/main/com/zipline/controller/message/MessageTemplateController.class
  apiserver/service/src/main/java/com/zipline/service/schedule/dto/request/ScheduleCreateRequestDTO.java
Labels: 🛠️ Fix

#415 chore: test 환경에서 swagger 읽기 전용으로 수정
  apiserver/controller/src/main/resources/application-test.yml
Labels: 🧹 Chore

#411 feat: 문자 발송 시 관심 지역 변수 치환 로직 추가
  apiserver/infrastructure/src/main/java/com/zipline/repository/region/RegionRepository.java
  apiserver/service/src/main/java/com/zipline/service/message/MessageServiceImpl.java
  apiserver/service/src/main/java/com/zipline/service/message/dto/request/SendMessageRequestDTO.java
Labels: ✨ Feat
