Repository Kernel360/Kernel360-KDEV4-ZIPLINE, pull requests merged in 2025-03, with the labels that each got.

#10 배포 설정 수정
  .github/workflows/cicd.yml
  .gitignore
  Dockerfile
  build.gradle
  db/Dockerfile
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/java/com/zipline/ZiplineBackendApplicationTests.java
Labels: Chore, CI/CD

#13 feat: 로그인, 회원가입 기능 구현
  src/main/java/com/zipline/auth/controller/AgentController.java
  src/main/java/com/zipline/auth/dto/AgentRequestDto.java
  src/main/java/com/zipline/auth/dto/AgentResponseDto.java
  src/main/java/com/zipline/auth/dto/AgentUpdatePasswordRequestDto.java
  src/main/java/com/zipline/auth/dto/TokenDto.java
  src/main/java/com/zipline/auth/entity/Agent.java
  src/main/java/com/zipline/auth/entity/Authority.java
  src/main/java/com/zipline/auth/repository/AgentRepository.java
  src/main/java/com/zipline/auth/service/AgentService.java
  src/main/java/com/zipline/auth/service/CustomAgentDetailService.java
  src/main/java/com/zipline/global/config/SecurityConfig.java
  src/main/java/com/zipline/global/exception/custom/AgentNotFoundException.java
  src/main/java/com/zipline/global/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/zipline/global/jwt/JwtFilter.java
  src/main/java/com/zipline/global/jwt/JwtSecurityConfig.java
  src/main/java/com/zipline/global/jwt/TokenProvider.java
Labels: Feat

#22 chore : QueryDSL 설정
  build.gradle
  src/main/java/com/zipline/global/config/QuerydslConfig.java
Labels: 🧹 Chore

#24 chore: 의존성 추가(Validation, Mockito)
  build.gradle
Labels: 🧹 Chore

#23 rename: 파일 및 컬럼명 수정
  src/main/java/com/zipline/auth/controller/AgentController.java
  src/main/java/com/zipline/auth/dto/AgentResponseDto.java
  src/main/java/com/zipline/auth/dto/AgentUpdatePasswordRequestDto.java
  src/main/java/com/zipline/auth/entity/Authority.java
  src/main/java/com/zipline/auth/repository/AgentRepository.java
  src/main/java/com/zipline/auth/service/AgentService.java
  src/main/java/com/zipline/controller/UserController.java
  src/main/java/com/zipline/dto/TokenRequestDto.java
  src/main/java/com/zipline/dto/TokenResponseDto.java
  src/main/java/com/zipline/dto/UserRequestDto.java
  src/main/java/com/zipline/dto/UserResponseDto.java
  src/main/java/com/zipline/entity/Authority.java
  src/main/java/com/zipline/entity/User.java
  src/main/java/com/zipline/global/config/SecurityConfig.java
  src/main/java/com/zipline/global/exception/custom/AgentNotFoundException.java
  src/main/java/com/zipline/global/exception/custom/UserNotFoundException.java
  src/main/java/com/zipline/global/jwt/TokenProvider.java
  src/main/java/com/zipline/repository/UserRepository.java
  src/main/java/com/zipline/service/CustomUserDetailService.java
  src/main/java/com/zipline/service/UserService.java
  src/main/resources/application-dev.properties
Labels: ✏️ Rename

#33 hotfix: SecurityConfig 수정
  src/main/java/com/zipline/global/config/SecurityConfig.java
  src/main/java/com/zipline/repository/UserRepository.java
  src/main/java/com/zipline/service/CustomUserDetailService.java
  src/main/java/com/zipline/service/UserService.java
Labels: 🔥 HotFix

#35 feat: Customer 등록
  src/main/java/com/zipline/controller/CustomerController.java
  src/main/java/com/zipline/dto/CustomerRegisterRequestDTO.java
  src/main/java/com/zipline/entity/Customer.java
  src/main/java/com/zipline/global/exception/GlobalExceptionHandler.java
  src/main/java/com/zipline/repository/CustomerRepository.java
  src/main/java/com/zipline/service/CustomerService.java
Labels: ✨ Feat
